name: codecrafters-http-server
version: 0.1.0.0
license: BSD3

default-extensions:
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - base >= 4.19 && < 5
  - network # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - mtl
  - optparse-applicative
  - pipes
  - pipes-network
  - safe
  - text

library:
  source-dirs: src
  exposed-modules:
    - Options
    - Server
    - ServerEnv
    - ServerM
  dependencies:
    - attoparsec
    - bytestring-encoding
    - directory
    - filepath
    - pipes-attoparsec
    - text-show
    - transformers

executables:
  codecrafters-http-server-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-http-server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
